### ISSUE TITLE
Licensing

### ISSUE THREAD

**Issue by TheKrafter** [RoseSMP/wiki#2]
Should this really be under the Apache? There is more content than code, so i think that at least the content should be under [CC-BY-SA 4.0](https://creativecommons.org/licenses/by-sa/4.0/). We should include the [little icon](https://creativecommons.org/choose/results-one?license_code=by-sa&amp;jurisdiction=&amp;version=4.0&amp;lang=en) that is a link to the creative commons page for it.

**Comment by fizzrepo** [comment]
Yeah, let's change the license.

**Comment by TheKrafter** [comment]
I added CC-BY-SA 4.0 with commit a8ddc49. Please make sure there isnt *no* license, or it's under exclusive copyright: https://choosealicense.com/no-permission/
