### ISSUE TITLE
list-of-all-pages does not fulfill its purpose

### ISSUE THREAD

**Issue by TheKrafter** [RoseSMP/wiki#8]
It should link to each page, and shouldn't include `/cmds` or `/meta`. It would also be good if it was in a bulleted list, and listed in alphabetic order for simple finding. It would be good if there was a header for each letter section. 
I'm not sure exactly how to implement this unless its done manually, so ill leave it as an issue for now.

**Comment by fizzrepo** [comment]
Agreed, for now we've got a basic thing going and I hope to add a more advanced implementation later.

**Comment by TheKrafter** [comment]
this might help: https://github.com/rukbotto/jekyll-index-pages

**Comment by TheKrafter** [comment]
yeah, i'll have to use jekyll-index-pages

**Comment by TheKrafter** [comment]
im not gonna use `jekyll-index-pages` because it's either not very well documented, or i need to learn a LOT more about jekyll to use it.

**Comment by TheKrafter** [comment]
still having trouble with this one

**Comment by TheKrafter** [comment]
this should work
